name: release-linux

on:
  push:
    tags:
      - '*'

jobs:
  release-linux:
    name: release-linux
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm@^7

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Pack for linux
        run: |
          rm -rf ./.github
          npm run pack:linux

      - name: Create debian package
        run: |
          npm run build:deb
          npm run build:deb-checksum

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './dist/installers/*.*'
          tag: ${{ github.ref }}
          file_glob: true

